# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GoodList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('originalPrice', models.CharField(max_length=100)),
                ('presentPrice', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'goodslist',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('userpassword', models.CharField(max_length=256)),
                ('userhead', models.CharField(default='defaultHead.jpg', max_length=256)),
                ('token', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
