# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanfu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotsingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('originalPrice', models.CharField(max_length=100)),
                ('presentPrice', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hotsingle',
            },
        ),
        migrations.CreateModel(
            name='Mens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('originalPrice', models.CharField(max_length=100)),
                ('presentPrice', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mens',
            },
        ),
        migrations.CreateModel(
            name='Newhot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('originalPrice', models.CharField(max_length=100)),
                ('presentPrice', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'newhot',
            },
        ),
        migrations.CreateModel(
            name='Womnes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('originalPrice', models.CharField(max_length=100)),
                ('presentPrice', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'womens',
            },
        ),
    ]
