# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanfu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('isselect', models.BooleanField(default=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanfu.Goodsdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanfu.User')),
            ],
            options={
                'db_table': 'sanfu_cart',
            },
        ),
    ]
