# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanfu', '0002_hotsingle_mens_newhot_womnes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Womnes',
            new_name='Womens',
        ),
    ]
