# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanfu', '0003_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(),
        ),
    ]
