# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanfu', '0003_user_userhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userhead',
            field=models.CharField(default='static/img/headImg/defaultHead.jpg', max_length=256),
        ),
    ]
