# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanfu', '0004_auto_20181108_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdetail',
            name='name',
            field=models.CharField(default='o', max_length=200),
        ),
    ]
