# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanfu', '0005_goodsdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetail',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
