# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanfu', '0006_auto_20181109_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=1)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanfu.User')),
            ],
            options={
                'db_table': 'sanfu_order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanfu.Goodsdetail')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanfu.Order')),
            ],
            options={
                'db_table': 'sanfu_ordergoods',
            },
        ),
    ]
